// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mstecs_back.Helpers;

namespace mstecs_back.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210718190852_Usuarios")]
    partial class Usuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mstecs_back.Entities.usuarios", b =>
            {
                b.Property<int>("id_usuario")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("nombre")
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("password_hash")
                    .HasColumnType("varbinary(max)");

                b.Property<byte[]>("password_salt")
                    .HasColumnType("varbinary(max)");

                b.Property<string>("correo")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("id_rol")
                    .HasColumnType("int");

                b.HasKey("id_usuario");

                b.ToTable("usuarios");
            });
#pragma warning restore 612, 618
        }
    }
}
